/**
* awesome.
* Documentation of our awesome API.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.skyit.model

import dev.skyit.model.Lesson
import dev.skyit.model.Review

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param catId 
 * @param difficulty 
 * @param duration 
 * @param lessons 
 * @param name 
 * @param reviews 
 * @param students 
 * @param teacherId 
 * @param teachers 
 * @param url 
 * @param workspaceId 
 */

data class Course (
    @Json(name = "_id")
    val id: kotlin.String? = null,
    @Json(name = "cat_id")
    val catId: kotlin.String? = null,
    @Json(name = "difficulty")
    val difficulty: kotlin.Int? = null,
    @Json(name = "duration")
    val duration: kotlin.Int? = null,
    @Json(name = "lessons")
    val lessons: kotlin.Array<Lesson>? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "reviews")
    val reviews: kotlin.Array<Review>? = null,
    @Json(name = "students")
    val students: kotlin.Array<kotlin.String>? = null,
    @Json(name = "teacher_id")
    val teacherId: kotlin.String? = null,
    @Json(name = "teachers")
    val teachers: kotlin.Array<kotlin.String>? = null,
    @Json(name = "url")
    val url: kotlin.String? = null,
    @Json(name = "workspace_id")
    val workspaceId: kotlin.String? = null
)

