/**
* awesome.
* Documentation of our awesome API.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.skyit.model

import dev.skyit.model.Video

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param materials 
 * @param students 
 * @param video 
 */

data class Lesson (
    @Json(name = "_id")
    val id: kotlin.String? = null,
    @Json(name = "materials")
    val materials: kotlin.Array<kotlin.String>? = null,
    @Json(name = "students")
    val students: kotlin.Array<kotlin.String>? = null,
    @Json(name = "video")
    val video: Video? = null
)

