/**
* awesome.
* Documentation of our awesome API.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.skyit.model


import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param createdAt 
 * @param email 
 * @param token 
 * @param userType 
 */

data class Session (
    @Json(name = "_id")
    val id: kotlin.Array<kotlin.Int>? = null,
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,
    @Json(name = "email")
    val email: kotlin.String? = null,
    @Json(name = "token")
    val token: kotlin.String? = null,
    @Json(name = "user_type")
    val userType: kotlin.Long? = null
)

