/**
* awesome.
* Documentation of our awesome API.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.skyit.model


import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param assignments 
 * @param courses 
 * @param email 
 * @param name 
 */

data class Student (
    @Json(name = "_id")
    val id: kotlin.String? = null,
    @Json(name = "assignments")
    val assignments: kotlin.Array<kotlin.String>? = null,
    @Json(name = "courses")
    val courses: kotlin.Array<kotlin.String>? = null,
    @Json(name = "email")
    val email: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null
)

