/**
* awesome.
* Documentation of our awesome API.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.skyit.model


import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param name 
 * @param type 
 * @param url 
 */

data class Workspace (
    @Json(name = "_id")
    val id: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "type")
    val type: kotlin.Long? = null,
    @Json(name = "url")
    val url: kotlin.String? = null
)

